before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    binary: tiny-todo
    ldflags:
      - -s -w -X github.com/lukecarr/tiny-todo/internal/info.Version={{.Tag}} -X github.com/lukecarr/tiny-todo/internal/info.Commit={{.FullCommit}} -X github.com/lukecarr/tiny-todo/internal/info.Date={{.Date}}
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    goarm:
      - '5'
      - '6'
      - '7'
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: lukecarr
    name: tiny-todo
