before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: tiny-todo
    ldflags:
      - -s -w -X github.com/lukecarr/tiny-todo/internal/info.Version={{.Tag}} -X github.com/lukecarr/tiny-todo/internal/info.Commit={{.FullCommit}} -X github.com/lukecarr/tiny-todo/internal/info.Date={{.Date}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - freebsd_amd64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_amd64

archives:
  - replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: lukecarr
    name: tiny-todo
